### ISSUE TITLE
Add Additional Block Type

### ISSUE THREAD

**Issue by mrjarbenne** [hwdsb/reveal-presentations#2] opened 2021-09-05 01:15 UTC
I'm adding Media and Text as an allowed block type. Despite adding the requisite type here: 

https://github.com/hwdsb/reveal-presentations/blob/63e39a04b959cab24b1b931b2ed34e63d1e43d76/includes/admin-block.php#L148

I'm seeing an issue where the heading text beside the media isn't rendering on the slide.

Post Editor:

<img width="1206" alt="2021-09-04_21-04-47" src="https://user-images.githubusercontent.com/480667/132111753-6c6619df-41df-47f4-a5f2-d6140ab284b6.png">

Frontend: 

<img width="1206" alt="2021-09-04_21-07-48" src="https://user-images.githubusercontent.com/480667/132111766-f06bde3a-b13e-4b21-8e55-b20d8efc22ea.png">

Note I've changed the text to black to rule out style issues.

Site in question is https://416.commons.hwdsb.on.ca/

**Comment by r-a-y** [comment] 2021-09-05 19:57
Should be fixed in commit 9d18894. I was doing some weird logic to try and reconstruct the slide content, but that isn't necessary.

**Comment by mrjarbenne** [comment] 2021-09-06 00:22
Looks great. Thanks.

**Comment by mrjarbenne** [comment] 2021-09-07 13:02
![2021-09-07_09-04-49](https://user-images.githubusercontent.com/480667/132349963-bdee19f5-1650-42d4-acfd-6b8af50a3c1e.png)

@r-a-y any chance that change has resulted in the content overlapping on a slide by slide basis? 

https://416.commons.hwdsb.on.ca/presentation/announcements/#/slide-3699

**Comment by r-a-y** [comment] 2021-09-07 20:08
This issue is not related.

The problem is the author of the "Land Acknowledgment" slide wrote some content outside the slide block. I've readjusted their content to fit within the slide. I've also identified some styling issues, mostly with spacing. See commit ca8fef6.

**Comment by mrjarbenne** [comment] 2021-09-08 00:56
Nice catch. I'll try to make that more apparent in the instructions. 

We can't force the content into the slide block can we?

I wonder if we should hide speaker notes to make the interface cleaner?

**Comment by mrjarbenne** [comment] 2021-09-08 01:39
I'm going to close this and start another thread.

**Closed as completed** 2021-09-08 01:39 UTC
